### PR TITLE
update harness (dev.harrel) with support for draft 2019-09

### PR DESCRIPTION
**Pull request by harrel56**
----
:books: Documentation preview :books:: https://bowtie-json-schema--602.org.readthedocs.build/en/602/

### CODE REVIEW

**Comment by harrel56** [comment]
Wanted to be a bit more explicit with naming my implementation but the IHOP schema is pretty strict. `dev.harrel.json-schema` is fine but it would probably make more sense to use java/gradle notation like `dev.harrel:json-schema`. Maybe you could consider allowing `:` in the implementation name :P

**Comment by Julian** [comment]
Fine with that! Feel free to modify.

**Comment by harrel56** [comment]
hmm, seems like my change did not take effect - should I change it somewhere else?

**Comment by Julian** [comment]
Run `pre-commit run` locally and it will fix the other place (which is [here](https://github.com/bowtie-json-schema/bowtie/blob/main/tests/fauxmplementations/lintsonschema/schemas/io.json#L80), unfortunately there's some file duplication to support one of the test cases and Docker not being able to include files outside of a given root directory.

**Comment by Julian** [comment]
I'm not sure honestly why pre-commit.ci didn't fix that automatically, maybe it doesn't understand that's a changed file, so there may be a small bug in the pre-commit hook which does this check, not sure.

**Comment by harrel56** [comment]
Didn't I change that file? https://github.com/bowtie-json-schema/bowtie/pull/602/files#diff-ec66c7052f7e2f942fb00efe8feea3f56e09d3b190adebc4e79bf648ca5ebd00

**Comment by Julian** [comment]
Oh indeed.. weird. Will look after lunch.

**Comment by Julian** [comment]
Ah the issue is because the job runs with the prod version of Bowtie (and it needs to for other reasons). Not sure if there's an obvious fix for this kind of change then other than doing it in two PRs. But will ignore.

**Comment by harrel56** [comment]
nice, thanks!

**Pull request merged**
