### PR TITLE
Run JSON Toolkit on 2019-09

### PR DESCRIPTION
**Pull request by jviotti**
----
📚 Documentation preview 📚: https://bowtie-json-schema--1427.org.readthedocs.build/en/1427/

### CODE REVIEW

**Comment by Julian** [comment]
Thanks!

**Comment by jviotti** [comment]
Let me know when it is deployed so I can proudly add the new README badge :D

**Comment by Julian** [comment]
Just pushed a release so should be live in a few minutes!

**Comment by jviotti** [comment]
Added. Thank you!

**Pull request merged**
