### PR TITLE
add openapi-processor runner

### PR DESCRIPTION
**Pull request by hauner**
new version of https://github.com/bowtie-json-schema/bowtie/pull/422

I tried to squash the commits on my side but that didn't work too well. Here is a new version with a clean history.

----
:books: Documentation preview :books:: https://bowtie-json-schema--439.org.readthedocs.build/en/439/

### CODE REVIEW

**Comment by hauner** [comment]
the pre-commit still complains

```
ktlint (kotlin implementations)................................................Failed
- hook id: ktlint
- files were modified by this hook
```

can we see which file it wants to change ? When I run it locally with `"--format"` it does not change any file.

**Comment by hauner** [comment]
add logging to trace may help.. but I can't see its full output. I just see `(output truncated)` after a few trace lines.

**Comment by Julian** [comment]
> can we see which file it wants to change ? When I run it locally with "--format" it does not change any file.

When I run it locally I get plenty of changes. Here's the diff in case it helps:

```diff
diff --git a/implementations/java-openapiprocessor/build.gradle.kts b/implementations/java-openapiprocessor/build.gradle.kts
index 0474f3c..02f98ae 100644
--- a/implementations/java-openapiprocessor/build.gradle.kts
+++ b/implementations/java-openapiprocessor/build.gradle.kts
@@ -50,8 +50,8 @@ tasks {
                 "validator.version" to libs.versions.validator.get(),
                 "validator.homepage" to "https://github.com/openapi-processor/openapi-parser",
                 "validator.issues" to "https://github.com/openapi-processor/openapi-parser/issues",
-                "java.build.version" to libs.versions.build.jdk.get()
-            )
+                "java.build.version" to libs.versions.build.jdk.get(),
+            ),
         )
     }
 
diff --git a/implementations/java-openapiprocessor/src/main/kotlin/Runner.kt b/implementations/java-openapiprocessor/src/main/kotlin/Runner.kt
index 8b1a06f..1fae9fe 100644
--- a/implementations/java-openapiprocessor/src/main/kotlin/Runner.kt
+++ b/implementations/java-openapiprocessor/src/main/kotlin/Runner.kt
@@ -20,7 +20,7 @@ import java.util.stream.Stream
 class Runner(
     private val input: BufferedReader,
     private val output: BufferedWriter,
-    private val error: BufferedWriter
+    private val error: BufferedWriter,
 ) {
     private val mapper = createMapper()
     private val config = Configuration()
diff --git a/implementations/java-openapiprocessor/src/main/kotlin/commands/Request.kt b/implementations/java-openapiprocessor/src/main/kotlin/commands/Request.kt
index 8b9aeb3..7ad0289 100644
--- a/implementations/java-openapiprocessor/src/main/kotlin/commands/Request.kt
+++ b/implementations/java-openapiprocessor/src/main/kotlin/commands/Request.kt
@@ -6,12 +6,12 @@ import com.fasterxml.jackson.annotation.JsonTypeInfo
 @JsonTypeInfo(
     use = JsonTypeInfo.Id.NAME,
     include = JsonTypeInfo.As.EXISTING_PROPERTY,
-    property = "cmd"
+    property = "cmd",
 )
 @JsonSubTypes(
     JsonSubTypes.Type(name = "start", value = StartRequest::class),
     JsonSubTypes.Type(name = "stop", value = StopRequest::class),
     JsonSubTypes.Type(name = "dialect", value = DialectRequest::class),
-    JsonSubTypes.Type(name = "run", value = RunRequest::class)
+    JsonSubTypes.Type(name = "run", value = RunRequest::class),
 )
 interface Request
diff --git a/implementations/java-openapiprocessor/src/main/kotlin/commands/RunCmd.kt b/implementations/java-openapiprocessor/src/main/kotlin/commands/RunCmd.kt
index 30e9a44..9e44be2 100644
--- a/implementations/java-openapiprocessor/src/main/kotlin/commands/RunCmd.kt
+++ b/implementations/java-openapiprocessor/src/main/kotlin/commands/RunCmd.kt
@@ -16,14 +16,14 @@ class Case(
     val comment: String?,
     val schema: Any,
     val registry: Map<URI, Any>?,
-    val tests: List<Test>
+    val tests: List<Test>,
 )
 
 data class Test(
     val description: String,
     val comment: String? = null,
     val instance: Any?,
-    val valid: Boolean?
+    val valid: Boolean?,
 )
 
 data class RunRequest(val seq: Int, val case: Case) : Request
@@ -40,8 +40,8 @@ class RunCmd(private val cfg: Configuration) : Request {
                 "errored" to true,
                 "context" to mapOf(
                     "message" to ex.message,
-                    "traceback" to stacktrace(ex)
-                )
+                    "traceback" to stacktrace(ex),
+                ),
             )
         }
     }
@@ -79,14 +79,14 @@ class RunCmd(private val cfg: Configuration) : Request {
 
             results.add(
                 mutableMapOf<String, Any>(
-                    "valid" to step.isValid
-                )
+                    "valid" to step.isValid,
+                ),
             )
         }
 
         return mapOf(
             "seq" to request.seq,
-            "results" to results
+            "results" to results,
         )
     }
 }
diff --git a/implementations/java-openapiprocessor/src/main/kotlin/commands/StartCmd.kt b/implementations/java-openapiprocessor/src/main/kotlin/commands/StartCmd.kt
index 2998fcb..34d5fbf 100644
--- a/implementations/java-openapiprocessor/src/main/kotlin/commands/StartCmd.kt
+++ b/implementations/java-openapiprocessor/src/main/kotlin/commands/StartCmd.kt
@@ -22,8 +22,8 @@ class StartCmd {
                 "version" to properties.getVersion(),
                 "dialects" to SchemaVersion.entries.map { it.schemaUri },
                 "homepage" to properties.getHomepage(),
-                "issues" to properties.getIssues()
-            )
+                "issues" to properties.getIssues(),
+            ),
         )
     }

```

**Comment by hauner** [comment]
hmm, surprising that it uses different rules. The pre-commit doesn't seem to configure any specific rules. So I thought adding the ktlint gradle plugin to my local build would be the same.

Tripping over another stupid rule ;-)

Thanks!!

**Comment by hauner** [comment]
Thanks as well for your support :-)

**Pull request closed without merging**
