### PR TITLE
rust-boon: upgrade to v0.2

### PR DESCRIPTION
**Pull request by santhosh-tekuri**
with this update, all tests should pass.

### CODE REVIEW

**Comment by Julian** [comment]
Thanks. Seems like it. If you know how to fix the security vulnerability notice for your package, and/or if you know how to retrieve its version at runtime, a follow-up PR would be great.

**Comment by santhosh-tekuri** [comment]
which security vulnerability notice. the link you provided in earlier pr https://github.com/bowtie-json-schema/bowtie/security/dependabot/14 is broken.

do you have any details about it.

**Comment by Julian** [comment]
Oh, I guess it may be private or something by default. 

Here's a screenshot, seems like you're depending on a package with a CVE:

Screenshot_20230224-103833

**Comment by Julian** [comment]
(FWIW I took a quick look at the time bug tracker and it seemed they seem to say the package is basically abandoned and to use chrono instead or something)

**Comment by santhosh-tekuri** [comment]
I am using `chrono` only which in turn depends on `time`. below is my dependency tree:

```
├── boon v0.2.0
│   ├── base64 v0.21.0
│   ├── chrono v0.4.23
│   │   ├── iana-time-zone v0.1.53
│   │   │   └── core-foundation-sys v0.8.3
│   │   ├── num-integer v0.1.45
│   │   │   └── num-traits v0.2.15
│   │   │       [build-dependencies]
│   │   │       └── autocfg v1.1.0
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.1.0
│   │   ├── num-traits v0.2.15 (*)
│   │   └── time v0.1.45
│   │       └── libc v0.2.139
```

**Comment by santhosh-tekuri** [comment]
may be explicitly adding `time = "0.2"` should fix the issue

**Comment by Julian** [comment]
Sorry, the reverse, it's chrono that's unmaintainedish and time that isn't: https://github.com/chronotope/chrono/issues/602


(But I'm neither a rust dev nor at my computer at the moment so you're likely in a much better spot to figure out the right fix)

**Pull request merged**
