### PR TITLE
Remove colorama from test requirements

### PR DESCRIPTION
**Pull request by adwait-godbole**
For some reason when I ran `pip-compile --strip-extras test-requirements.in` for adding `pexpect` it added `colorama` as a test dependency [here](https://github.com/bowtie-json-schema/bowtie/pull/1020/files#diff-fac4c6890301d4de5c3f4266837803d5240c84a3d8b6c735bbc6a64c39d2f94e) (via `click` and `pytest`) which wasn't already present in our `test-requirements.txt`, so no need!. 

Also removed the `.split` logic and used `.removeprefix` just like how we do in the other case.

----
📚 Documentation preview 📚: https://bowtie-json-schema--1049.org.readthedocs.build/en/1049/

### CODE REVIEW

**Comment by Julian** [comment]
Cool, thanks, though wait, the only way to update the requirements files should basically be by running `nox -s requirements`, is that what you ran now?

**Comment by adwait-godbole** [comment]
Ohh I thought we add the dependency in `test-requirements.in` and then run `pip-compile --strip-extras test-requirements.in`. I did this way. Sorry :(

**Comment by adwait-godbole** [comment]
Reference:- https://github.com/bowtie-json-schema/bowtie/pull/1020/files#diff-fac4c6890301d4de5c3f4266837803d5240c84a3d8b6c735bbc6a64c39d2f94e

**Comment by Julian** [comment]
All good

> pip-compile --strip-extras test-requirements.in to generate test-requirements.txt

**Comment by adwait-godbole** [comment]
> This will do the same thing essentially if you run it with the same Python version, and if you remember to also update the other requirements files. The nox command exists basically to make sure you don't make a mistake there essentially, so yeah if that's not what you ran you can run it now and it'll fix up the files.

Thanks! I will remember this for the future but I confirmed [here](https://github.com/bowtie-json-schema/bowtie/pull/1020/files#diff-fac4c6890301d4de5c3f4266837803d5240c84a3d8b6c735bbc6a64c39d2f94e), `colorama` is the only unnecessary one that was added for now. Nothing else.

**Comment by adwait-godbole** [comment]
So the fix is done 👍

**Comment by Julian** [comment]
Great, merged, thanks.

**Pull request merged**
