### PR TITLE
Remove 1.7.0 from `java-json-schema` because of breaking changes

### PR DESCRIPTION
**Pull request by adwait-godbole**
@Julian The [previous run](https://github.com/bowtie-json-schema/bowtie/actions/runs/10562198672) passed for all of the versions except this one. I didn't notice that this version had some serious breaking changes while adding support for `Draft 7`. Now if I try to modify the code just for this single version, that will make it ugly. It's better to skip this one given that `1.7.1` is correctly adding the support for `Draft 7`. 

You will have to re-run the workflow again after this. Sorry for the trouble :(. Should've caught this on my fork earlier on. Thanks!

----
📚 Documentation preview 📚: https://bowtie-json-schema--1482.org.readthedocs.build/en/1482/

### CODE REVIEW

**Comment by adwait-godbole** [comment]
@Julian can you please also trigger `versioned-report.yml` for `java-json-schema`. Thanks.

**Comment by Julian** [comment]
I did! https://github.com/bowtie-json-schema/bowtie/actions/runs/10563165557

**Comment by adwait-godbole** [comment]
No I am talking about `versioned-report.yml` so we can generate versioned reports of `java-json-schema` since we have built the images now. :)

**Comment by adwait-godbole** [comment]
> I did! https://github.com/bowtie-json-schema/bowtie/actions/runs/10563165557

yes this was `images.yml`

**Comment by Julian** [comment]
Ah, right, done.

**Pull request merged**
