### PR TITLE
rust-boon: upgrade to v0.3

### PR DESCRIPTION
**Pull request by santhosh-tekuri**

### CODE REVIEW

**Comment by santhosh-tekuri** [comment]
the site still shows rust-boon v0.2.1

**Comment by Julian** [comment]
I haven't done a release (of Bowtie), it'll be done when I'm back to a computer.

**Comment by Julian** [comment]
The image build seems to be failing again.

**Comment by santhosh-tekuri** [comment]
Can we split image building for AMD and ARM into separate tasks, so that if ARM build fails it won't affect AMD build. and the website can be generated from AMD images

**Pull request merged**
