### PR TITLE
badges: generant pass pct json files

### PR DESCRIPTION
**Pull request by santhosh-tekuri**

### CODE REVIEW

**Comment by santhosh-tekuri** [comment]
related issue #55

**Comment by santhosh-tekuri** [comment]
@Julian plz do codereview

**Comment by santhosh-tekuri** [comment]
@Julian yes. I was aware of the work in progress by other PR

since there is no process in PR for week, I jumped in with fresh PR

**Comment by Julian** [comment]
Newer programmers need more time to work on things. Even for a more seasoned developer it's polite to first offer help before immediately jumping in. Please ask next time.

**Comment by Julian** [comment]
Thanks! Merged this after making a few minor tweaks (mainly using `pathlib.Path` objects) which you can see on `main` if you're curious. Otherwise this seems like a start definitely, thanks again.

I guess I was assuming all badges would be produced in one place (if not right now where we have multiple runs, at least eventually). But we can discuss that on the other PR.

Also I guess the badges here should probably be named something to do with their function -- so `badges/implementation/passing/draft7.json` or whatever -- but we can make that tweak once we have a second badge as well. Let me know if you have opinions there.

**Comment by santhosh-tekuri** [comment]
all badges are generated in the dir mentioned in cli argument

**Comment by Julian** [comment]
Right but with #203 someone generating all badges needs to know to run multiple different commands, yes? Or similarly the CI job now needs to run `bowtie info` as well, which it didn't before.

**Comment by santhosh-tekuri** [comment]
@Julian may be we can generate badges both in `info` and `report`;
in CI, we will just use `report` command to generate all badges

**Comment by Julian** [comment]
That's fine with me too yeah.

**Pull request merged**
