### PR TITLE
Added local metaschema

### PR DESCRIPTION
**Pull request by mwadams**
----
📚 Documentation preview 📚: https://bowtie-json-schema--1201.org.readthedocs.build/en/1201/

### CODE REVIEW

**Comment by Julian** [comment]
pre-commit is failing because you keep undoing clang-format's changes :) -- I don't care what formatting is used, but please either:

* tweak the settings so clang-format emits what you want
* leave it how clang-format puts it
* change to some other pre-commit hook that works the way you want

where I presume the above is in ascending order of effort*value.

**Comment by Julian** [comment]
(Normally pre-commit would straight up push a commit to revert what you have, but because your PR comes from an organization it does not have permissions to do so).

**Comment by mwadams** [comment]
> (Normally pre-commit would straight up push a commit to revert what you have, but because your PR comes from an organization it does not have permissions to do so).

Apologies - I realise I keep doing this; clang-format is not part of my toolchain and I have to remember to run it manually.

**Comment by Julian** [comment]
(If you install pre-commit run `pre-commit install` it will run automatically on commit.) Otherwise yeah I don't mind if you wait till push to find out, just making sure you weren't confused by the failures!

**Pull request merged**
