### PR TITLE
Show bowtie summary & bowtie smoke output in GITHUB_STEP_SUMMARY

### PR DESCRIPTION
**Pull request by sudo-jarvis**
This pull request addresses #850.

The goal is to emit the bowtie smoke output in images.yml workflow and bowtie summary output in report.yml workflow to the github actions summary.

----
📚 Documentation preview 📚: https://bowtie-json-schema--843.org.readthedocs.build/en/843/

### CODE REVIEW

**Comment by sudo-jarvis** [comment]
Hi @Julian , I think in the workflows it installs and uses the latest released build of bowtie. The markdown changes arent yet released so I am not able to test whether its working or not.

**Comment by Julian** [comment]
Makes sense. I'll do a release in a few hours then.

**Comment by sudo-jarvis** [comment]
Hi @Julian , tested these changes now. They work fine.

Please have a look:
Screenshot 2024-02-11 at 10 09 28 AM
Screenshot 2024-02-11 at 10 12 55 AM

**Comment by Julian** [comment]
Great!

**Pull request merged**
