### PR TITLE
Deploy new react frontend

### PR DESCRIPTION
**Pull request by harrel56**

### CODE REVIEW

**Comment by harrel56** [comment]
Hmm, forgot about that it's not possible to deploy GH pages from non-main branches. Gonna try a different approach then

**Comment by harrel56** [comment]
Ideally, deploying UI to GH pages should not trigger whole test suite. I guess now it's fine as it takes ~10min, but later it could get problematic. Separating these 2 things is a bit tricky, but it certainly can be done

**Comment by Julian** [comment]
Definitely definitely up for separating them now that the frontend is separate!

**Comment by harrel56** [comment]
Sure, I can do this separation in scope of this PR but it's gonna be on the next day 💤

**Comment by harrel56** [comment]
Gonna close it and merge it from different branch

**Pull request closed without merging**
