### PR TITLE
badges: generate version json files

### PR DESCRIPTION
**Pull request by santhosh-tekuri**

### CODE REVIEW

**Comment by santhosh-tekuri** [comment]
ready for review

**Comment by Julian** [comment]
Let me know what you think about the end of https://github.com/bowtie-json-schema/bowtie/pull/202#issuecomment-1497608730 -- namely, I *think* we should be able to generate these badges at the same time as the other ones, rather than distributing them across multiple commands -- when we speak to any implementation we get a list of all the dialects it supports. (Maybe we're not writing that out right now into what's piped into `bowtie report`, but we could in theory do so, it's in memory.)

**Comment by VishrutAggarwal** [comment]
Hi @Julian & @santhosh-tekuri,

I apologize for the late reply, I was caught up in some medical stuff and was on bed rest for a few days, I am feeling better now.

I have gone through the previous [PR](https://github.com/bowtie-json-schema/bowtie/pull/202), I find a lot of similarities and understand what I had to work on. Basically I understand what my next steps should've been. I guess I was slow in that 😅.

Nonetheless, I would've liked a heads up on that matter. I am also at fault for not having updated on my end.

For now, should I work on adding other badges to it or work on some other good first issue? @Julian 

I would still like to work on bowtie. If I am to work on some other issue, I have [Issue#54](https://github.com/bowtie-json-schema/bowtie/issues/54) in mind. I find it up to my skill level, though I learned a lot working on the badge implementation, I think I should first have a solid contribution to the project before I take up on a task where I have to learn a lot.

Again I apologize for the late replies and delay in updates, I had just undergone a procedure and was strictly asked to be off-screen for that matter.

**Comment by santhosh-tekuri** [comment]
@VishrutAggarwal you can work on the changes @Julian requested in this PR

in PR #202 I added method to generate passing badges in `report` command.
this PR generated supported version badges in `info` command.

@Julian suggested generating supported version badges also in `report` command.
you can work on that. you can also refer to the code in this PR

**Comment by Julian** [comment]
Replaced by #260.

**Pull request closed without merging**
