### PR TITLE
Bug Fix: Somehow the former gives error in terms of some url library missing during the workflow

### PR DESCRIPTION
**Pull request by sudo-jarvis**
I had tested the workflow using, since the latest benchmark changes were not there in the latest release:

This works fine
```
     - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Bowtie
         run: |
          pip install -e .
```

However now using, 

This doesnt work
```
- name: Install Bowtie
        uses: ./
```

Since the latest release has been done, the workflow is failing on the python script step saying `url` library not found. I dont understand why though @Julian . Both code should work the same functionality wise right ?

ERROR:

```
Run python - <<EOF
  python - <<EOF
  from pathlib import Path
  from bowtie._benchmarks import combine_benchmark_reports_to_serialized as combine
  
  Path("draft[2](https://github.com/sudo-jarvis/bowtie/actions/runs/10547927252/job/29221319098#step:5:2)020-12.json").write_text(
      combine(
          Path("benchmarks-draft2020-12").iterdir()
      )
  )
  
  EOF
  shell: /usr/bin/bash -e {0}
  
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/runner/work/bowtie/bowtie/bowtie/__init__.py", line [5](https://github.com/sudo-jarvis/bowtie/actions/runs/10547927252/job/29221319098#step:5:5), in <module>
    from url import URL
ModuleNotFoundError: No module named 'url'
Error: Process completed with exit code 1.
```

Failed job link: https://github.com/sudo-jarvis/bowtie/actions/runs/10547927252/job/29221319098#step:5:19

----
📚 Documentation preview 📚: https://bowtie-json-schema--1476.org.readthedocs.build/en/1476/

### CODE REVIEW

**Comment by Julian** [comment]
You need to use the `python` executable from the virtualenv bowtie was installed into, which is why it doesn't work. We (in the action) happen to install using pipx -- so this is quite hacky -- but we're doing internal things here.
The fix here isn't right, if you're going to install the package yourself you should just not use the action to install Bowtie -- but probably for now given we accepted the temporary hacky python script inlined we should possibly just check if pipx has a way to tell us where the virtualenv is / where that python lives, and you run using that one.

**Comment by sudo-jarvis** [comment]
Hmm this worked @Julian . Had to use --sytem flag or else it was giving error that venv not found.

```
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: hynek/setup-cached-uv@v2

      - name: Install Bowtie
        run: | 
          uv pip install --system .
```

**Comment by sudo-jarvis** [comment]
I'll push this then.

**Comment by sudo-jarvis** [comment]
Done & tested it @Julian.

**Comment by sudo-jarvis** [comment]
@Julian, sorry for bothering but please cancel the old workflow run and rerun it again

**Comment by Julian** [comment]
Done!

**Pull request merged**
