### PR TITLE
Show compliance summaries across all implementations for a specific JSON Schema Vocabulary

### PR DESCRIPTION
**Pull request by AgniveshChaubey**
# Work in Progress

**Note:** This PR is submitted early to get some feedback and suggestions for the ongoing work.

This pull request addresses [Issue #248](https://github.com/bowtie-json-schema/bowtie/issues/248). The primary goal is to create a cross-implementation page that displays compliance summaries across all implementations for a specific JSON Schema Vocabulary.

### Implemented Features

- Implemented the function to extract the names of vocabularies.
- Completed the placement of the dropdown menu (open to suggestions for alternative placements).

image

Search Query Logic

- Logic to add the search query for vocabulary has been implemented successfully.

In order to get more clarity I'm currently looking for some feedback/suggestions on how to proceed with filtering the `reportData` based on the selected vocabulary. Any suggestion would be really appreciated. :)

----
📚 Documentation preview 📚: https://bowtie-json-schema--708.org.readthedocs.build/en/708/

### CODE REVIEW

**Comment by Julian** [comment]
Nice! I haven't taken a close look at this yet, though I think part of what you're asking depends on #27 to happen (specifically the data needed to filter on vocabularies isn't present yet in report output).

But I've actually made a small bit of progress on that this past week, I can have another look at what's needed when I look at this PR.

And welcome back!

**Comment by AgniveshChaubey** [comment]
>  I've actually made a small bit of progress on that this past week ...

Any updates on your progress?

I have tried to extract the vocabulary list from the current data itself, but that's a brute-force approach. For now, consider not reviewing this PR. Ping me when you are done with the updates, and I'll make changes in this PR accordingly.

**Comment by Julian** [comment]
Hey! 

> Any updates on your progress?

I made some more, but not entirely done actually unfortunately, I got distracted by a few other things that also were in the way.

> Ping me when you are done with the updates, and I'll make changes in this PR accordingly.

I will and thanks again! Hopefully I'll spend a few more days here in the next week or so and then be able to do so. Really appreciated!

**Comment by Julian** [comment]
One specific thing we *do* need by the way, which I noticed as part of the refactoring, is integration tests between the UI and backend particularly for the report processing -- i.e. we need tests that call `bowtie foo` and then parse the output of that with `parseReportData` from the UI, and which complain if that integration doesn't work (#706 is partially that).

I have to try to write one -- we have now either a place to do so in the backend test suite or also in the frontend one, and it really doesn't matter where, as long as one place has at least one, because otherwise it's quite easy to break the frontend.

**Comment by AgniveshChaubey** [comment]
> One specific thing we do need, by the way, which I noticed as part of the refactoring, is integration tests....

I only have a very basic understanding of testing, but this task seems like a good start to getting started with testing as well. However, I am a bit messed up with my schedule these days, so I'll give it a shot in the upcoming weeks and will let you know if I require any help.

**Comment by Julian** [comment]
Slow progress here, but I just added a first test finally, it lives here now: https://github.com/bowtie-json-schema/bowtie/blob/main/frontend/src/data/parseReportData.test.ts so we can finally make changes to the report without the UI completely breaking.

More to be done there but we're on the way finally.

**Comment by AgniveshChaubey** [comment]
Closing this PR as it is too outdated!

**Pull request closed without merging**
